import React from "react";
import { FlipCard } from "./FlipCard";

const servicesData = [
  {
    th: "ROKSPACE",
    title: "FIBER",
    description: "ootb fiber customer support content",
    bigDescHead: `Digitalize your fiber customer support in weeks using plug-and-play customer support content`,
    bigDesc: `<p style="text-align: center;">As a fiber operator, you face significant costs and challenges in developing and maintaining content for all customer support channels. Your customers expect intuitive, effortless service experiences, like those offered by ChatGPT. However, the complexity of backend systems, a wide range of devices, and limited automation make it difficult to meet these expectations.</p><br />
    <p style="text-align: center;">-High costs &amp; effort for support content<br>
-High customer expectations for intuitive service<br>
-Complex technology with backend &amp; many devices</p>
<br />
<p style="text-align: center;"><span class="TextRun SCXW188556759 BCX4" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW188556759 BCX4">As a result, many customers avoid self-service channels and turn to customer </span><span class="NormalTextRun SCXW188556759 BCX4">support</span><span class="NormalTextRun SCXW188556759 BCX4"> representatives instead. They themselves struggle with high call volumes, limited </span><span class="NormalTextRun SCXW188556759 BCX4">training</span><span class="NormalTextRun SCXW188556759 BCX4"> and complexity of customer issues. This leads to long wait times, higher interaction costs, and dissatisfied customers, while the potential </span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW188556759 BCX4">of</span><span class="NormalTextRun SCXW188556759 BCX4"> self-</span><span class="NormalTextRun SCXW188556759 BCX4">care</span> <span class="NormalTextRun SCXW188556759 BCX4">remains</span><span class="NormalTextRun SCXW188556759 BCX4"> untapped. Changing the status quo typically requires significant investments, and building </span><span class="NormalTextRun SCXW188556759 BCX4">customer support</span><span class="NormalTextRun SCXW188556759 BCX4"> from scratch </span><span class="NormalTextRun SCXW188556759 BCX4">isn’t</span> <span class="NormalTextRun SCXW188556759 BCX4">a viable</span> <span class="NormalTextRun SCXW188556759 BCX4">option</span><span class="NormalTextRun SCXW188556759 BCX4">. This leaves customer </span><span class="NormalTextRun SCXW188556759 BCX4">support</span><span class="NormalTextRun SCXW188556759 BCX4"> executives in a dilemma of how to </span><span class="NormalTextRun SCXW188556759 BCX4">initiate</span> <span class="NormalTextRun SCXW188556759 BCX4">truly significant</span><span class="NormalTextRun SCXW188556759 BCX4"> improvements.</span></span><span class="EOP SCXW188556759 BCX4" data-ccp-props="{}">&nbsp;</span></p>`,
  },
  {
    th: "ROKSPACE",
    title: "HFC",
    description: "ootb HFC customer support content",
    bigDescHead: `Digitalize your DOCSIS customer support in weeks using plug-and-play customer support content `,
    bigDesc: `<p style="text-align: center;"><span class="TextRun SCXW139340451 BCX4" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW139340451 BCX4">As </span><span class="NormalTextRun SCXW139340451 BCX4">an HFC</span><span class="NormalTextRun SCXW139340451 BCX4"> operator, you face significant costs and challenges in developing and </span><span class="NormalTextRun SCXW139340451 BCX4">maintaining</span> <span class="NormalTextRun SCXW139340451 BCX4">content for </span><span class="NormalTextRun SCXW139340451 BCX4">all customer </span><span class="NormalTextRun SCXW139340451 BCX4">support channels</span><span class="NormalTextRun SCXW139340451 BCX4">. </span><span class="NormalTextRun SCXW139340451 BCX4">Your c</span><span class="NormalTextRun SCXW139340451 BCX4">ustomers expect intuitive, </span><span class="NormalTextRun SCXW139340451 BCX4">effortless</span><span class="NormalTextRun SCXW139340451 BCX4"> service experiences, like those offered by ChatGPT. However, the complexity of backend systems, a wide range of devices, and limited automation make it difficult to meet these expectations</span><span class="NormalTextRun SCXW139340451 BCX4">.</span></span><span class="EOP SCXW139340451 BCX4" data-ccp-props="{}">&nbsp;</span></p><br /><p style="text-align: center;">-HFC operators face high costs and challenges in managing support content.<br>
-Customers expect seamless, AI-like service experiences.<br>
-Complex systems, diverse devices, and limited automation hinder meeting these expectations.</p><br /><p style="text-align: center;"><span class="TextRun SCXW237196018 BCX4" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW237196018 BCX4">As a result, many customers avoid self-service channels and turn to customer </span><span class="NormalTextRun SCXW237196018 BCX4">support</span><span class="NormalTextRun SCXW237196018 BCX4"> representatives instead. They themselves struggle with high call volumes, limited </span><span class="NormalTextRun SCXW237196018 BCX4">training</span><span class="NormalTextRun SCXW237196018 BCX4"> and complexity of customer issues. This leads to long wait times, higher interaction costs, and dissatisfied customers, while the potential </span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW237196018 BCX4">of</span><span class="NormalTextRun SCXW237196018 BCX4"> self-</span><span class="NormalTextRun SCXW237196018 BCX4">care</span> <span class="NormalTextRun SCXW237196018 BCX4">remains</span><span class="NormalTextRun SCXW237196018 BCX4"> untapped. Changing the status quo typically requires significant investments, and building </span><span class="NormalTextRun SCXW237196018 BCX4">customer support</span><span class="NormalTextRun SCXW237196018 BCX4"> from scratch </span><span class="NormalTextRun SCXW237196018 BCX4">isn’t</span> <span class="NormalTextRun SCXW237196018 BCX4">a viable</span> <span class="NormalTextRun SCXW237196018 BCX4">option</span><span class="NormalTextRun SCXW237196018 BCX4">. This leaves customer </span><span class="NormalTextRun SCXW237196018 BCX4">support</span><span class="NormalTextRun SCXW237196018 BCX4"> executives in a dilemma of how to </span><span class="NormalTextRun SCXW237196018 BCX4">initiate</span> <span class="NormalTextRun SCXW237196018 BCX4">truly significant</span><span class="NormalTextRun SCXW237196018 BCX4"> improvements.</span></span><span class="EOP SCXW237196018 BCX4" data-ccp-props="{}">&nbsp;</span></p><br/><p style="text-align: center;">-Customers bypass self-service, overloading support teams.<br>
-Long wait times and high costs stem from complex issues and limited training.<br>
-Major improvements require investment, leaving executives unsure of the next steps.</p><br>
<p style="text-align: center;"><span class="TextRun SCXW238676427 BCX4" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW238676427 BCX4">ROKSPACE </span><span class="NormalTextRun SCXW238676427 BCX4">HFC</span><span class="NormalTextRun SCXW238676427 BCX4"> is </span><span class="NormalTextRun SCXW238676427 BCX4">a comprehensive library of </span><span class="NormalTextRun SCXW238676427 BCX4">DOCSIS</span><span class="NormalTextRun SCXW238676427 BCX4"> customer support</span><span class="NormalTextRun SCXW238676427 BCX4"> capabilities</span><span class="NormalTextRun SCXW238676427 BCX4"> – c</span><span class="NormalTextRun SCXW238676427 BCX4">overing all</span> <span class="NormalTextRun SCXW238676427 BCX4">HFC</span> <span class="NormalTextRun SCXW238676427 BCX4">issues</span><span class="NormalTextRun SCXW238676427 BCX4"> that customers may </span><span class="NormalTextRun SCXW238676427 BCX4">encounter</span><span class="NormalTextRun SCXW238676427 BCX4">. Instead of creating and managing all customer support content by yourself, it grants you access to preconfigured telco best practices. Using our powerful AI inference engine, every customer support channel can utilize ROKSPACE </span><span class="NormalTextRun SCXW238676427 BCX4">HFC</span><span class="NormalTextRun SCXW238676427 BCX4"> content to boost KPIs such as Resolution Rates, Average Handling Times, or Recaller Rates. ROKSPACE </span><span class="NormalTextRun SCXW238676427 BCX4">HFC</span><span class="NormalTextRun SCXW238676427 BCX4"> is</span><span class="NormalTextRun SCXW238676427 BCX4"> ready to deploy, ensuring a go-to-market time of just a few weeks.</span><span class="NormalTextRun SCXW238676427 BCX4"> You deliver intuitive digital experiences to your customers while reducing effort and cost. </span><span class="NormalTextRun SCXW238676427 BCX4">Transform your customer </span><span class="NormalTextRun SCXW238676427 BCX4">support</span><span class="NormalTextRun SCXW238676427 BCX4"> in weeks using preconfigured, best-practice telco </span><span class="NormalTextRun SCXW238676427 BCX4">customer support</span><span class="NormalTextRun SCXW238676427 BCX4"> content</span><span class="NormalTextRun SCXW238676427 BCX4">.</span></span><span class="EOP SCXW238676427 BCX4" data-ccp-props="{}">&nbsp;</span></p><br /><p style="text-align: center;">-ROKSPACE HFC offers a ready-to-use DOCSIS support library for all HFC issues.<br>
-AI-powered best practices enhance KPIs like Resolution Rates and Handling Times.<br>
-Deploy in weeks, cutting costs while improving digital customer experiences.</p><br>
`,
  },
  {
    th: "ROKSPACE",
    title: "PULSE",
    description: "Proactively address issues before they impact CX",
    bigDescHead: `Proactively resolve customer issues and ensure growing revenue from 3rd and 1st party services`,
    bigDesc: `<p style="text-align: center;"><span class="TextRun SCXW228949727 BCX4" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW228949727 BCX4">Driven by an increasing number of connected devices, Smart Home systems, OTT services, and 3rd party offerings, the growing scope and complexity of telecom infrastructure puts significant pressure on providers. Effective monitoring and proactively resolving problems is becoming more difficult, while telecom companies </span><span class="NormalTextRun SCXW228949727 BCX4">remain</span><span class="NormalTextRun SCXW228949727 BCX4"> responsible for ensuring seamless functionality across all services. Managing these challenges without effective tools makes it increasingly difficult to prevent and resolve issues proactively. Where systems already provide proactive functionality like alarming, the information is not fully </span><span class="NormalTextRun SCXW228949727 BCX4">leveraged</span><span class="NormalTextRun SCXW228949727 BCX4"> for proactive resolutions</span><span class="NormalTextRun SCXW228949727 BCX4"> or tied back to customer impact.</span></span></p><br><p style="text-align: center;">-Growing device numbers and service complexity strain telecom providers.<br>
-Monitoring and proactive issue resolution are becoming more challenging.<br>
-Existing systems generate alerts but fail to drive proactive solutions.</p><br><p style="text-align: center;"><span class="TextRun SCXW204655519 BCX4" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW204655519 BCX4">Frequent outages and service failures, regardless of their origin, severely damage customer satisfaction and lead to churn. For telecom companies, this immensely threatens the viability of OTT or bundled services, which are critical for revenue. Without proactive solutions, reactive issue resolution becomes costly, labor-intensive, and inefficient, delaying root cause identification and preventing continuous improvement.</span></span></p><br><p style="text-align: center;">-Frequent outages hurt customer satisfaction and increase churn.<br>
-Service failures threaten the viability of OTT and bundled offerings.<br>
-Reactive troubleshooting is costly, slow, and hinders continuous improvement.</p><br>`,
  },
  {
    th: "ROKSPACE",
    title: "OAN",
    description: "Open up new revenue streams as network owner",
    bigDescHead: `Resell customer support solutions to ISPs to save effort, reduce costs and unlock new revenue streams `,
    bigDesc: `<p style="text-align: center;"><span class="TextRun SCXW230327238 BCX4" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW230327238 BCX4">The shared use of physical network infrastructure by multiple providers makes managing, monitoring, and </span><span class="NormalTextRun SCXW230327238 BCX4">maintaining</span><span class="NormalTextRun SCXW230327238 BCX4"> the network </span><span class="NormalTextRun SCXW230327238 BCX4">highly complex</span><span class="NormalTextRun SCXW230327238 BCX4">. When faults or outages occur, </span><span class="NormalTextRun SCXW230327238 BCX4">identifying</span><span class="NormalTextRun SCXW230327238 BCX4"> the cause becomes challenging because issues can originate at </span><span class="NormalTextRun SCXW230327238 BCX4">different levels</span><span class="NormalTextRun SCXW230327238 BCX4">—end customer, ISP, or network owner. ISPs often lack </span><span class="NormalTextRun SCXW230327238 BCX4">expertise</span><span class="NormalTextRun SCXW230327238 BCX4"> in direct customer support, creating </span><span class="NormalTextRun SCXW230327238 BCX4">additional</span><span class="NormalTextRun SCXW230327238 BCX4"> work for network owners.</span> <span class="NormalTextRun SCXW230327238 BCX4">Manual</span><span class="NormalTextRun SCXW230327238 BCX4"> error identification and resolution lead</span><span class="NormalTextRun SCXW230327238 BCX4">s</span><span class="NormalTextRun SCXW230327238 BCX4"> to delays, increased workload, and growing customer dissatisfaction.</span></span></p><br><p style="text-align: center;">-Shared network infrastructure complicates management, monitoring, and maintenance.<br>
-Fault identification is challenging, as issues can stem from customers, ISPs, or network owners.<br>
-Manual troubleshooting causes delays, higher workloads, and customer dissatisfaction.</p><br><p style="text-align: center;"><span class="TextRun SCXW124094510 BCX4" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW124094510 BCX4">This situation results in significant challenges for all parties. Network owners face higher costs and increased workloads, even when they are not responsible for the problem. ISPs suffer financial losses due to unresolved customer issues caused by a lack of problem-solving capabilities. End customers experience dissatisfaction because they lack self-service solutions to resolve issues quickly. The absence of automation further compounds the problem, as </span><span class="NormalTextRun SCXW124094510 BCX4">i</span><span class="NormalTextRun SCXW124094510 BCX4">dentifying</span> <span class="NormalTextRun SCXW124094510 BCX4">root causes and responsibilities takes </span><span class="NormalTextRun SCXW124094510 BCX4">s</span><span class="NormalTextRun SCXW124094510 BCX4">ignificant time</span><span class="NormalTextRun SCXW124094510 BCX4">,</span><span class="NormalTextRun SCXW124094510 BCX4"> delaying resolutions and straining resources.</span></span><span class="EOP SCXW124094510 BCX4" data-ccp-props="{}">&nbsp;</span></p><br><p style="text-align: center;">-Network owners bear high costs and workloads.<br>
-ISPs lose revenue from unresolved issues.<br>
-Customers lack self-service, and delays worsen without automation.</p><br><p style="text-align: center;"><span class="TextRun SCXW66936142 BCX4" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW66936142 BCX4">ROKSPACE OAN localizes root causes and automates troubleshooting wherever possible. This reduces workload, shortens resolution times, and improves overall efficiency. </span><span class="NormalTextRun SCXW66936142 BCX4">ROKSPACE OAN</span><span class="NormalTextRun SCXW66936142 BCX4"> enables network owners to resell intelligent customer s</span><span class="NormalTextRun SCXW66936142 BCX4">upport </span><span class="NormalTextRun SCXW66936142 BCX4">solutions to ISPs. Therefore, it reduces costs and effort while opening new revenue streams. </span><span class="NormalTextRun SCXW66936142 BCX4">Utilizing ROKSPACE OAN, </span><span class="NormalTextRun SCXW66936142 BCX4">ISPs can offer advanced self-care applications that help end customers resolve issues more efficiently, leading to enhanced satisfaction and fewer escalated problems for network owners.</span><span class="NormalTextRun SCXW66936142 BCX4"> Network owners </span><span class="NormalTextRun SCXW66936142 BCX4">benefit</span><span class="NormalTextRun SCXW66936142 BCX4"> from </span><span class="NormalTextRun SCXW66936142 BCX4">additional</span><span class="NormalTextRun SCXW66936142 BCX4"> revenue, meeting SLAs more effectively and differentiating their offerings.</span></span></p><br><p style="text-align: center;">-ROKSPACE OAN automates troubleshooting, reducing workload and resolution times.<br>
-Network owners can resell support solutions to ISPs, cutting costs and creating new revenue streams.<br>
-ISPs offer self-care tools, improving customer satisfaction and minimizing escalations.</p>`,
  },
  {
    th: "ROKSPACE",
    title: "OMNX",
    description: "Data-driven customer journeys on all channels",
    bigDescHead: `Empower every single customer touchpoint to save cost and improve customer experiences – without additional effort`,
    bigDesc: `<p style="text-align: center;"><span class="TextRun SCXW132009937 BCX4" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW132009937 BCX4">The wide variety of customer segments requires addressing different communication preferences. Each </span><span class="NormalTextRun SCXW132009937 BCX4">customer support </span><span class="NormalTextRun SCXW132009937 BCX4">channel must be capable of resolving issues comprehensively while also enabling seamless transitions to other channels</span><span class="NormalTextRun SCXW132009937 BCX4">. To meet </span><span class="NormalTextRun SCXW132009937 BCX4">customer </span><span class="NormalTextRun SCXW132009937 BCX4">expectations, every channel should </span><span class="NormalTextRun SCXW132009937 BCX4">have access to real-time data and should offer AI-driven decision-making.</span><span class="NormalTextRun SCXW132009937 BCX4"> However, creating and managing content for each channel individually demands significant effort. Every channel has specific requirements</span><span class="NormalTextRun SCXW132009937 BCX4">, which increases the workload. Despite these efforts, service quality often varies between channels due to the fragmented approach and siloed team structures.</span></span></p><br><p style="text-align: center;">-Diverse customer segments require tailored communication across support channels.<br>
-Channels must resolve issues seamlessly with real-time data and AI-driven decisions.<br>
-Managing content separately increases workload, leading to inconsistent service quality.</p><br><p style="text-align: center;">T<span class="TextRun SCXW86442004 BCX4" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW86442004 BCX4">his fragmented approach results in </span><span class="NormalTextRun SCXW86442004 BCX4">high costs</span><span class="NormalTextRun SCXW86442004 BCX4"> and effort for developing, </span><span class="NormalTextRun SCXW86442004 BCX4">maintaining</span><span class="NormalTextRun SCXW86442004 BCX4">, and </span><span class="NormalTextRun SCXW86442004 BCX4">optimizing</span><span class="NormalTextRun SCXW86442004 BCX4"> channel-specific content. Additionally, the lack of a unified </span><span class="NormalTextRun SCXW86442004 BCX4">solution</span><span class="NormalTextRun SCXW86442004 BCX4"> across teams prevents effective collaboration and the realization of shared improvement opportunities, further increasing costs and delaying progress. Customers often face inconsistent service quality, leading to repeated queries and poor experiences. This, in turn, lowers the adoption rate of automated customer </span><span class="NormalTextRun SCXW86442004 BCX4">support</span><span class="NormalTextRun SCXW86442004 BCX4"> channels and prevents the achievement of NextGen service quality across all channels.</span></span></p><br><p style="text-align: center;">-Fragmented content management drives high costs and effort.<br>
-Lack of a unified solution hinders collaboration and slows progress.<br>
-Inconsistent service quality leads to poor experiences and low automation adoption.</p><br><p style="text-align: center;"><span class="TextRun SCXW129777702 BCX4" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW129777702 BCX4">ROKSPACE OMNX addresses these challenges with AI-driven, highly personalized service interactions that fuel </span><span class="NormalTextRun SCXW129777702 BCX4">every </span><span class="NormalTextRun SCXW129777702 BCX4">customer s</span><span class="NormalTextRun SCXW129777702 BCX4">upport </span><span class="NormalTextRun SCXW129777702 BCX4">channel</span><span class="NormalTextRun SCXW129777702 BCX4">. It enhances the adoption of self-care channels by driving data-driven decisions and enabling automated actions. Furthermore, it allows seamless transitions between channels while </span><span class="NormalTextRun SCXW129777702 BCX4">r</span><span class="NormalTextRun SCXW129777702 BCX4">etaining</span> <span class="NormalTextRun SCXW129777702 BCX4">the context of prior interactions, saving </span><span class="NormalTextRun SCXW129777702 BCX4">t</span><span class="NormalTextRun SCXW129777702 BCX4">ime</span> <span class="NormalTextRun SCXW129777702 BCX4">and ensuring a consistent and positive customer experience. ROKSPACE OMNX simplifies content management by using a single, unified content base</span><span class="NormalTextRun SCXW129777702 BCX4"> for all customer support channels,</span><span class="NormalTextRun SCXW129777702 BCX4"> significantly reducing the effort and costs associated with content creation and maintenance. ROKSPACE OMNX not only lowers costs but also improves the adoption of digital, automated s</span><span class="NormalTextRun SCXW129777702 BCX4">upport </span><span class="NormalTextRun SCXW129777702 BCX4">channels, paving the way for more efficient and scalable customer </span><span class="NormalTextRun SCXW129777702 BCX4">support</span><span class="NormalTextRun SCXW129777702 BCX4">.</span></span></p><br><p style="text-align: center;">-ROKSPACE OMNX enables AI-driven, personalized support across all channels.<br>
-It enhances self-care adoption with data-driven decisions and automated actions.<br>
-A unified content base reduces costs, ensures consistency, and improves scalability.</p>`,
  },
  {
    th: "ROKSPACE",
    title: "MOBILE",
    description: "ootb mobile customer support content",
    bigDescHead: `Digitalize your mobile customer support in weeks using plug-and-play customer support content`,
    bigDesc: `<p style="text-align: center;"><span class="TextRun SCXW98103987 BCX4" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW98103987 BCX4">As a result, many customers avoid self-service channels and turn to customer </span><span class="NormalTextRun SCXW98103987 BCX4">support</span><span class="NormalTextRun SCXW98103987 BCX4"> representatives instead. They themselves struggle with high call volumes, limited </span><span class="NormalTextRun SCXW98103987 BCX4">training</span><span class="NormalTextRun SCXW98103987 BCX4"> and complexity of customer issues. This leads to long wait times, higher interaction costs, and dissatisfied customers, while the potential </span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW98103987 BCX4">of</span><span class="NormalTextRun SCXW98103987 BCX4"> self-</span><span class="NormalTextRun SCXW98103987 BCX4">care</span> <span class="NormalTextRun SCXW98103987 BCX4">remains</span><span class="NormalTextRun SCXW98103987 BCX4"> untapped. Changing the status quo typically requires significant investments, and building </span><span class="NormalTextRun SCXW98103987 BCX4">customer support</span><span class="NormalTextRun SCXW98103987 BCX4"> from scratch </span><span class="NormalTextRun SCXW98103987 BCX4">isn’t</span> <span class="NormalTextRun SCXW98103987 BCX4">a viable</span> <span class="NormalTextRun SCXW98103987 BCX4">option</span><span class="NormalTextRun SCXW98103987 BCX4">. This leaves customer </span><span class="NormalTextRun SCXW98103987 BCX4">support</span><span class="NormalTextRun SCXW98103987 BCX4"> executives in a dilemma of how to </span><span class="NormalTextRun SCXW98103987 BCX4">initiate</span> <span class="NormalTextRun SCXW98103987 BCX4">truly significant</span><span class="NormalTextRun SCXW98103987 BCX4"> improvements.</span></span><span class="EOP SCXW98103987 BCX4" data-ccp-props="{}">&nbsp;</span></p><br><p style="text-align: center;">-Customers bypass self-service, overloading support teams.<br>
-High call volumes, limited training, and complex issues increase wait times and costs.<br>
-Significant improvements require investment, leaving executives uncertain about the next steps.</p><br><p style="text-align: center;"><span class="TextRun SCXW98103987 BCX4" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW98103987 BCX4">As a result, many customers avoid self-service channels and turn to customer </span><span class="NormalTextRun SCXW98103987 BCX4">support</span><span class="NormalTextRun SCXW98103987 BCX4"> representatives instead. They themselves struggle with high call volumes, limited </span><span class="NormalTextRun SCXW98103987 BCX4">training</span><span class="NormalTextRun SCXW98103987 BCX4"> and complexity of customer issues. This leads to long wait times, higher interaction costs, and dissatisfied customers, while the potential </span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW98103987 BCX4">of</span><span class="NormalTextRun SCXW98103987 BCX4"> self-</span><span class="NormalTextRun SCXW98103987 BCX4">care</span> <span class="NormalTextRun SCXW98103987 BCX4">remains</span><span class="NormalTextRun SCXW98103987 BCX4"> untapped. Changing the status quo typically requires significant investments, and building </span><span class="NormalTextRun SCXW98103987 BCX4">customer support</span><span class="NormalTextRun SCXW98103987 BCX4"> from scratch </span><span class="NormalTextRun SCXW98103987 BCX4">isn’t</span> <span class="NormalTextRun SCXW98103987 BCX4">a viable</span> <span class="NormalTextRun SCXW98103987 BCX4">option</span><span class="NormalTextRun SCXW98103987 BCX4">. This leaves customer </span><span class="NormalTextRun SCXW98103987 BCX4">support</span><span class="NormalTextRun SCXW98103987 BCX4"> executives in a dilemma of how to </span><span class="NormalTextRun SCXW98103987 BCX4">initiate</span> <span class="NormalTextRun SCXW98103987 BCX4">truly significant</span><span class="NormalTextRun SCXW98103987 BCX4"> improvements.</span></span><span class="EOP SCXW98103987 BCX4" data-ccp-props="{}">&nbsp;</span></p><br><p style="text-align: center;">-Customers avoid self-service, increasing pressure on support teams.<br>
-High call volumes, limited training, and complex issues cause long wait times and high costs.<br>
-Significant improvements require major investment, leaving executives unsure how to proceed.</p><br><p style="text-align: center;"><span class="TextRun SCXW211283086 BCX4" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW211283086 BCX4">ROKSPACE </span><span class="NormalTextRun SCXW211283086 BCX4">MOBILE</span><span class="NormalTextRun SCXW211283086 BCX4"> is </span><span class="NormalTextRun SCXW211283086 BCX4">a comprehensive library of </span><span class="NormalTextRun SCXW211283086 BCX4">mobile</span><span class="NormalTextRun SCXW211283086 BCX4"> customer support</span><span class="NormalTextRun SCXW211283086 BCX4"> capabilities</span><span class="NormalTextRun SCXW211283086 BCX4"> – c</span><span class="NormalTextRun SCXW211283086 BCX4">overing all</span> <span class="NormalTextRun SCXW211283086 BCX4">mobile</span> <span class="NormalTextRun SCXW211283086 BCX4">issues</span><span class="NormalTextRun SCXW211283086 BCX4"> that customers may </span><span class="NormalTextRun SCXW211283086 BCX4">encounter</span><span class="NormalTextRun SCXW211283086 BCX4">. Instead of creating and managing all customer support content by yourself, it grants you access to preconfigured telco best practices. Using our powerful AI inference engine, every customer support channel can utilize ROKSPACE </span><span class="NormalTextRun SCXW211283086 BCX4">MOBILE</span><span class="NormalTextRun SCXW211283086 BCX4"> content to boost KPIs such as Resolution Rates, Average Handling Times, or Recaller Rates. ROKSPACE </span><span class="NormalTextRun SCXW211283086 BCX4">MOBILE</span><span class="NormalTextRun SCXW211283086 BCX4"> is</span><span class="NormalTextRun SCXW211283086 BCX4"> ready to deploy, ensuring a go-to-market time of just a few weeks.</span><span class="NormalTextRun SCXW211283086 BCX4"> You deliver intuitive digital experiences to your customers while reducing effort and cost. </span><span class="NormalTextRun SCXW211283086 BCX4">Transform your customer </span><span class="NormalTextRun SCXW211283086 BCX4">support</span><span class="NormalTextRun SCXW211283086 BCX4"> in weeks using preconfigured, best-practice telco </span><span class="NormalTextRun SCXW211283086 BCX4">customer support</span><span class="NormalTextRun SCXW211283086 BCX4"> content</span><span class="NormalTextRun SCXW211283086 BCX4">.</span></span><span class="EOP SCXW211283086 BCX4" data-ccp-props="{}">&nbsp;</span></p><br>`,
  },
];

const Services = () => {
  return (
    <section
      id="services"
      className="min-h-screen flex flex-col justify-center items-center px-20"
    >
      <div className="md:grid md:grid-cols-3 gap-10 px-10 space-y-5">
        <div className="flex items-center text-right col-span-1">
          The ROKSPACE Telecoms Suite offers 6 distinct solutions to leverage AI
          technologies for optimized efficiency and cost reduction in customer
          operations. <br />
          <br /> Discover how ROKSPACE leverages Machine Learning, rule based
          decisioning and GenAI to drive a business goal-oriented AI
          orchestration of customer support.
        </div>
        <div className="md:col-span-2 flex gap-x-3 gap-y-6 flex-wrap">
          {servicesData.map((service, index) => (
            <FlipCard
              key={index}
              th={service.th}
              title={service.title}
              description={service.description}
              bigDescHead={service.bigDescHead}
              bigDesc={service.bigDesc}
            />
          ))}
        </div>
      </div>
    </section>
  );
};

export default Services;
